[package]
name = "screensaver-off"
version = "0.0.6"
authors = ["Max Gonzih <gonzih@gmail.com>"]

[dependencies]
sysinfo = "0.9.5"
log = "0.4.6"
env_logger = "0.6.1"
regex = "*"
dirs = "2.0.1"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_16"]
