[package]
name = "screensaver-off"
version = "0.0.6"
authors = ["Max Gonzih <gonzih@gmail.com>"]

[dependencies]
sysinfo = "0.14.7"
log = "0.4.11"
femme = "2"
anyhow = "1"
regex = "*"
dirs = "3"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_16"]
