[package]
name = "screensaver-off"
version = "0.0.6"
authors = ["Max Gonzih <gonzih@gmail.com>"]

[dependencies]
sysinfo = "0.14.4"
log = "0.4.10"
env_logger = "0.7.1"
regex = "*"
dirs = "3.0.0"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_16"]
