version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout
      - run: apt-get update
      - run: apt-get -y install libatk1.0-dev libpango1.0-dev
      - run: make build
