version: 2
jobs:
  build:
    docker:
      - image: nixos/nix
    steps:
      - checkout
      - echo "export PATH=$GOPATH/bin:$PATH" >> $BASH_ENV
      - run: nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
      - run: nix-channel --update
      - run: nix-env -i gnumake rustup
      - run: make rust-setup ci
