version: 2
jobs:
  build:
    docker:
      - image: nixos/nix
    steps:
      - checkout
      - run: nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
      - run: nix-channel --update
      - run: nix-env -i cmake rustup
      - run: make rust-setup ci
