version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: CI
          command: apt-get update && apt-get -y install make docker
      - run:
          name: CI
          command: make ci
